---
- name: "Building Docker Image"
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: "Installing Docker Python Extension"
      pip:
        name:
          - boto
          - boto3
          - botocore
      
    - name: "Listing all environment variable"
      shell: env
      register: env_variables
    - debug:
        var: env_variables
        
    - name: "Fetching Az Details"
      amazon.aws.aws_az_info:
      register: az_info

    - debug:
       var: az_info
