---
- name: "Building Docker Image"
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: "Fetching Az Details"
      amazon.aws.aws_az_info:
      register: az_info

    - debug:
       var: az_info
