---
- name: "Building Docker Image"
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - variables.yml
  tasks:
    - name: "Installing Docker Python Extension"
      pip:
        name: "{{ docker_extension }}"
          
    - name: "Fetching Az Details"
      amazon.aws.aws_az_info:
      register: az_info

    - debug:
       var: az_info
