name: CI

env:

  IMAGE_SHA: $GITHUB_SHA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "setting docker image tags"
        id: DOCKER_EXTRA_TAGS
        run: |
          echo "GITHUB_SHA_LONG=$(echo $GITHUB_SHA)" >> $GITHUB_ENV
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: "printing DOCKER_EXTRA_TAGS"
        run: echo ${{ env.GITHUB_SHA_SHORT }}
