name: CI

env:

  IMAGE_SHA: $GITHUB_SHA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout to branch"
        uses: actions/checkout@v3
        
      - name: "working directory"
        run: |
          ls -al
          pwd
          ansible --version
          python --version
          python3  --version
          touch /tmp/${DOCKER_ENV}
          echo "asdsd" > /tmp/${DOCKER_ENV}
          cat /tmp/${DOCKER_ENV}
        env:
          DOCKER_ENV: ${{ secrets.DOCKER_USERNAME }}
       
