name: CI

env:

  IMAGE_SHA: $GITHUB_SHA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout to branch"
        uses: actions/checkout@v3
        
      - name: "working directory"
        run: |
          ls -al
          pwd
          ansible --version
          python --version
          python3  --version
          touch /tmp/${DOCKER_ENV}
          echo "asdsd" > /tmp/${DOCKER_ENV}
          cat /tmp/${DOCKER_ENV}
        env:
          DOCKER_ENV: ${{ secrets.DOCKER_USERNAME }}
          
      - name: "running playing book"
        run: |
          ansible-playbook deployment.yml
        env:
          AWS_ACCESS_KEY_ID:: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
       
