name: CI

env:

  IMAGE_SHA: $GITHUB_SHA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout to branch"
        uses: actions/checkout@v3
        
      - name: "working directory"
        run: |
          ls -al
          pwd
          ansible --version
          which python --version
          which python3  --version
