name: CI

env:

  IMAGE_SHA: $GITHUB_SHA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout to branch"
        uses: actions/checkout@v3
        
      - name: "setting docker image tags"
        id: DOCKER_EXTRA_TAGS
        run: |
          echo "GITHUB_SHA_LONG=$(echo $GITHUB_SHA)" >> $GITHUB_ENV
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: "Login To DockerHub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: "Build And Push Image To Repository"
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          image: repo/image
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/myapp:latest
            ${{ secrets.DOCKER_USERNAME }}/myapp:${{ env.GITHUB_SHA_LONG }}
            ${{ secrets.DOCKER_USERNAME }}/myapp:${{ env.GITHUB_SHA_SHORT }}
