name: CI

env:

  IMAGE_SHA: $GITHUB_SHA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHORT_TAG: ${{  echo hello }}
    steps:
      - name: "Checkout to branch"
        run:
         echo env.SHORT_TAG
